/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a monitor
         * @description Registers a new monitor. Duplicate target URLs are allowed and each successful request creates a distinct monitor identity. Registration is not idempotent and does not establish that the target is safe to probe.
         */
        post: operations["registerMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a monitor */
        get: operations["getMonitor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitorId}/latest-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the latest terminal check result
         * @description Returns the latest terminal execution fact for the Monitor, ordered by terminal completion. Pending CheckRuns are not exposed and this read does not derive an up/down availability verdict.
         */
        get: operations["getLatestCheckResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitorId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current monitor availability
         * @description Read-only assessment from the latest terminal result. Future or older-than-120-second evidence is unknown; exactly 120 seconds is fresh. HTTP 200–299 is available; other valid HTTP statuses and probe failures are unavailable. Policy and execution failures are unknown. No terminal result returns unknown/no_result without evidence. All matched responses use no-store.
         */
        get: operations["getMonitorAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateMonitorRequest: {
            /**
             * @description Exact target text to register. The Monitoring domain accepts an absolute HTTP or HTTPS target with a hostname, rejects embedded userinfo and fragments, permits query strings and explicit ports, and preserves accepted input text. The public contract intentionally does not apply RFC 3986 format: uri because the existing domain parser can accept and preserve values outside that syntax. Registration validation is syntactic only and is not SSRF or execution-safety approval.
             * @example https://example.com/health?region=eu
             */
            targetUrl: string;
        };
        Monitor: {
            /**
             * Format: uuid
             * @description Stable monitor UUID. The public contract does not guarantee a UUID version.
             */
            id: string;
            /** @description Exact target text accepted at registration and preserved by the Monitoring domain. No RFC 3986 format constraint is applied. */
            targetUrl: string;
            /**
             * Format: date-time
             * @description Immutable monitor creation instant emitted with UTC domain semantics.
             */
            createdAt: string;
        };
        LatestCheckResult: components["schemas"]["LatestHTTPResponseResult"] | components["schemas"]["LatestFailureResult"] | components["schemas"]["LatestWorkerTimeoutResult"];
        LatestHTTPResponseResult: {
            /**
             * Format: uuid
             * @description Durable CheckRun UUID.
             */
            checkId: string;
            /** @constant */
            resultKind: "http_response";
            /** @description Final HTTP response status after safe redirect handling. */
            httpStatus: number;
            /** @description Monotonic probe duration in milliseconds. */
            durationMs: number;
            /**
             * Format: date-time
             * @description Persisted terminal completion instant.
             */
            completedAt: string;
        };
        LatestFailureResult: {
            /**
             * Format: uuid
             * @description Durable CheckRun UUID.
             */
            checkId: string;
            /** @enum {string} */
            resultKind: "dns_error" | "policy_rejected" | "timeout" | "connect_error" | "tls_error" | "protocol_error" | "internal_error";
            /** @description Monotonic duration until terminal failure classification. */
            durationMs: number;
            /**
             * Format: date-time
             * @description Persisted terminal completion instant.
             */
            completedAt: string;
        };
        LatestWorkerTimeoutResult: {
            /**
             * Format: uuid
             * @description Durable CheckRun UUID.
             */
            checkId: string;
            /** @constant */
            resultKind: "worker_timeout";
            /**
             * Format: date-time
             * @description Persisted terminal completion instant.
             */
            completedAt: string;
        };
        Problem: {
            /** Format: uri-reference */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        MonitorAvailability: components["schemas"]["AvailableMonitorAvailability"] | components["schemas"]["UnavailableMonitorAvailability"] | components["schemas"]["UnknownMonitorAvailability"] | components["schemas"]["NoResultMonitorAvailability"];
        MonitorAvailabilityEvidence: {
            /** Format: uuid */
            checkId: string;
            /** Format: date-time */
            completedAt: string;
        };
        AvailableMonitorAvailability: {
            /** @constant */
            status: "available";
            /** @constant */
            reason: "successful_response";
            /** Format: date-time */
            evaluatedAt: string;
            evidence: components["schemas"]["MonitorAvailabilityEvidence"];
        };
        UnavailableMonitorAvailability: {
            /** @constant */
            status: "unavailable";
            /** @enum {string} */
            reason: "unexpected_http_status" | "probe_failure";
            /** Format: date-time */
            evaluatedAt: string;
            evidence: components["schemas"]["MonitorAvailabilityEvidence"];
        };
        UnknownMonitorAvailability: {
            /** @constant */
            status: "unknown";
            /** @enum {string} */
            reason: "future_result" | "stale_result" | "policy_rejected" | "execution_failure";
            /** Format: date-time */
            evaluatedAt: string;
            evidence: components["schemas"]["MonitorAvailabilityEvidence"];
        };
        NoResultMonitorAvailability: {
            /** @constant */
            status: "unknown";
            /** @constant */
            reason: "no_result";
            /** Format: date-time */
            evaluatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMonitorRequest"];
            };
        };
        responses: {
            /** @description Monitor registered. */
            201: {
                headers: {
                    /** @description Relative reference for retrieving the created monitor. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            /** @description Malformed request content. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported request media type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request content is understood but violates the monitor contract. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Monitor persistence failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable monitor UUID. */
                monitorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitor found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            /** @description monitorId is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Monitor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Monitor persistence failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLatestCheckResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable monitor UUID. */
                monitorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest terminal execution result found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestCheckResult"];
                };
            };
            /** @description Monitor exists but has no terminal execution result yet. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description monitorId is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Monitor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Latest-result persistence read failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMonitorAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assessment. */
            200: {
                headers: {
                    /** @description Always bypass cached availability assessments. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorAvailability"];
                };
            };
            /** @description Request failed. */
            400: {
                headers: {
                    /** @description Always bypass cached availability assessments. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed. */
            404: {
                headers: {
                    /** @description Always bypass cached availability assessments. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed. */
            500: {
                headers: {
                    /** @description Always bypass cached availability assessments. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
